# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # nice!nano v2 board target after the ZMK Zephyr 4.1 migration
  # (see https://zmk.dev/blog/2025/12/09/zephyr-4-1#zmk-board-variant)
  - board: nice_nano//zmk
    shield: lily58_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano//zmk
    shield: lily58_right
  - board: nice_nano//zmk
    shield: settings_reset
